# Generated by Django 3.0.7 on 2020-09-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_auto_20200911_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='contactInfo',
            new_name='contact_info',
        ),
    ]
