# Generated by Django 3.0.7 on 2020-09-16 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_builder', '0003_auto_20200911_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('device_id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
