# Generated by Django 3.0.7 on 2020-09-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_enduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='end_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_builder.EndUser'),
        ),
    ]
