# Generated by Django 3.0.7 on 2020-10-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0005_resume_end_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='profile',
        ),
    ]
